Update Jenkinsfile1

diff --git a/Jenkinsfile1 b/Jenkinsfile1
--- a/Jenkinsfile1
+++ b/Jenkinsfile1
@@ -36,21 +36,21 @@ pipeline {
                // }
             //}
         //}
-        //stage('Install Dependencies') {
-          //  steps {
-            //    sh '''
-              //  cd bookmyshow-app
-                //ls -la  # Verify package.json exists
-                //if [ -f package.json ]; then
-                  //  rm -rf node_modules package-lock.json  # Remove old dependencies
-                    //npm install  # Install fresh dependencies
-                //else
-                  //  echo "Error: package.json not found in bookmyshow-app!"
-                    //exit 1
-                //fi
-                //'''
-            //}
-        //}
+        stage('Install Dependencies') {
+           steps {
+              sh '''
+            cd bookmyshow-app
+               ls -la  # Verify package.json exists
+               if [ -f package.json ]; then
+                 rm -rf node_modules package-lock.json  # Remove old dependencies
+               npm install  # Install fresh dependencies
+               else
+                 echo "Error: package.json not found in bookmyshow-app!"
+               exit 1
+               fi
+               '''
+            }
+        }
         //stage('OWASP FS Scan') {
           //  steps {
             //    dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
