Update Jenkinsfile1

diff --git a/Jenkinsfile1 b/Jenkinsfile1
--- a/Jenkinsfile1
+++ b/Jenkinsfile1
@@ -19,49 +19,49 @@ pipeline {
                 sh 'ls -la'  // Verify files after checkout
             }
         }
-        stage('SonarQube Analysis') {
-            steps {
-                withSonarQubeEnv('Sonar-token') {
-                    sh ''' 
-                    $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=BMS \
-                    -Dsonar.projectKey=BMS 
-                    '''
-                }
-            }
-        }
-        stage('Quality Gate') {
-            steps {
-                script {
-                    waitForQualityGate abortPipeline: false, credentialsId: 'Sonar-token'
-                }
-            }
-        }
-        stage('Install Dependencies') {
-            steps {
-                sh '''
-                cd bookmyshow-app
-                ls -la  # Verify package.json exists
-                if [ -f package.json ]; then
-                    rm -rf node_modules package-lock.json  # Remove old dependencies
-                    npm install  # Install fresh dependencies
-                else
-                    echo "Error: package.json not found in bookmyshow-app!"
-                    exit 1
-                fi
-                '''
-            }
-        }
-        stage('OWASP FS Scan') {
-            steps {
-                dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
-                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
-            }
-        }
-        stage('Trivy FS Scan') {
-            steps {
-                sh 'trivy fs . > trivyfs.txt'
-            }
-        }
+       // stage('SonarQube Analysis') {
+         //   steps {
+           //     withSonarQubeEnv('Sonar-token') {
+             //       sh ''' 
+               //     $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=BMS \
+                 //   -Dsonar.projectKey=BMS 
+                   // '''
+                //}
+            //}
+        //}
+       // stage('Quality Gate') {
+         //   steps {
+           //     script {
+             //       waitForQualityGate abortPipeline: false, credentialsId: 'Sonar-token'
+               // }
+            //}
+        //}
+        //stage('Install Dependencies') {
+          //  steps {
+            //    sh '''
+              //  cd bookmyshow-app
+                //ls -la  # Verify package.json exists
+                //if [ -f package.json ]; then
+                  //  rm -rf node_modules package-lock.json  # Remove old dependencies
+                    //npm install  # Install fresh dependencies
+                //else
+                  //  echo "Error: package.json not found in bookmyshow-app!"
+                    //exit 1
+                //fi
+                //'''
+            //}
+        //}
+        //stage('OWASP FS Scan') {
+          //  steps {
+            //    dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
+              //  dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
+            //}
+        //}
+        //stage('Trivy FS Scan') {
+          //  steps {
+            //    sh 'trivy fs . > trivyfs.txt'
+            //}
+        //}
         stage('Docker Build & Push') {
             steps {
                 script {
